export { default as AboutSection } from './AboutSection'
export { default as BlogSection } from './BlogSection'
export { default as ContactSection } from './ContactSection'
export { default as FooterSection } from './FooterSection'
export { default as HeroSection } from './HeroSection'
export { default as MethodSection } from './MethodSection'
export { default as ProjectsSection } from './ProjectsSection'
export { default as ServicesSection } from './ServicesSection'
